# Generated by Django 3.1.6 on 2021-03-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_services', '0002_auto_20210312_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='service_category',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
