# Generated by Django 3.1.6 on 2021-03-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_services', '0003_auto_20210312_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
