# Generated by Django 3.1.6 on 2021-03-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_services', '0004_delete_servicecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='service_category',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
