# Generated by Django 3.1.6 on 2021-03-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_orderlineitem_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_is_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
