# Generated by Django 3.1.6 on 2021-03-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderlineitem_product_is_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_is_service',
        ),
    ]
